version: "2"

linters:
  settings:
    staticcheck:
      checks:
        - "all"
        - "-SA4006" # False positive with Go 1.26 new(val) syntax; standalone staticcheck v0.7.0 handles it correctly
